#!/usr/bin/env bash
# go-guardian: SessionStart hook -- build binary (if needed) + session ID + staleness check
# Dual-mode: works as plugin (CLAUDE_PLUGIN_DATA set) or standalone (.go-guardian/).

set -euo pipefail

# ── Resolve paths (plugin vs fallback) ───────────────────────────────────────
if [[ -n "${CLAUDE_PLUGIN_DATA:-}" ]]; then
  MCP_BIN="${CLAUDE_PLUGIN_DATA}/go-guardian-mcp"
  DB_PATH="${CLAUDE_PLUGIN_DATA}/guardian.db"
  SOURCE_DIR="${CLAUDE_PLUGIN_ROOT}/mcp-server"
  GUARDIAN_DIR="${CLAUDE_PLUGIN_DATA}"
else
  GUARDIAN_DIR="${PWD}/.go-guardian"
  MCP_BIN="${GUARDIAN_DIR}/go-guardian-mcp"
  DB_PATH="${GUARDIAN_DIR}/guardian.db"
  SOURCE_DIR=""
fi

# ── Check ripgrep (required for agent/skill/search discovery) ────────────────
if ! command -v rg >/dev/null 2>&1; then
  echo "  go-guardian: ripgrep (rg) not found — agents, skills, and @file mentions may not load."
  echo "  Install: brew install ripgrep (macOS) | apt install ripgrep (Debian) | apk add ripgrep (Alpine)"
  echo "  Or set USE_BUILTIN_RIPGREP=0 after installing. Run /doctor to diagnose."
fi

# ── Build binary on first use or source change (plugin mode only) ────────────
if [[ -n "${SOURCE_DIR}" ]] && [[ -d "${SOURCE_DIR}" ]]; then
  CHECKSUM_FILE="${GUARDIAN_DIR}/.source-checksum"
  CURRENT_CHECKSUM=$(find "${SOURCE_DIR}" -path '*/node_modules' -prune -o -path '*/dist' -prune -o \( -name '*.go' -o -name 'go.sum' \) -print | sort | xargs cat 2>/dev/null | shasum -a 256 | cut -d' ' -f1)

  NEEDS_BUILD=false
  if [[ ! -x "${MCP_BIN}" ]]; then
    NEEDS_BUILD=true
  elif [[ ! -f "${CHECKSUM_FILE}" ]]; then
    NEEDS_BUILD=true
  elif [[ "$(cat "${CHECKSUM_FILE}" 2>/dev/null)" != "${CURRENT_CHECKSUM}" ]]; then
    NEEDS_BUILD=true
  fi

  if [[ "${NEEDS_BUILD}" == "true" ]]; then
    if command -v go >/dev/null 2>&1; then
      mkdir -p "${GUARDIAN_DIR}"
      (cd "${SOURCE_DIR}" && go build -ldflags="-s -w" -o "${MCP_BIN}" .) 2>/dev/null && {
        chmod +x "${MCP_BIN}"
        echo "${CURRENT_CHECKSUM}" > "${CHECKSUM_FILE}"
      } || true
    fi
  fi
fi

# ── Generate agentgateway configs (plugin mode only) ─────────────────────────
# GO_GUARDIAN_GATEWAY values: "docker" | "native" | "1" (auto-detect: docker > native)
if [[ -n "${CLAUDE_PLUGIN_ROOT:-}" ]] && [[ -d "${CLAUDE_PLUGIN_ROOT}/gateway/openapi" ]]; then
  OPENAPI_DIR="${CLAUDE_PLUGIN_ROOT}/gateway/openapi"

  # ── Native config (includes go-guardian stdio target) ──────────────────────
  GATEWAY_CONFIG="${GUARDIAN_DIR}/gateway-config.yaml"
  cat > "${GATEWAY_CONFIG}" <<GWEOF
# Auto-generated by go-guardian plugin — regenerated each session.
# Native mode: agentgateway --config ${GATEWAY_CONFIG}
binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        cors:
          allowOrigins: ["http://localhost:3000"]
          allowHeaders: [content-type, mcp-protocol-version, mcp-session-id]
          exposeHeaders: [mcp-session-id, mcp-protocol-version]
          maxAge: 100s
        csrf:
          additionalOrigins: ["http://localhost:3000"]
      backends:
      - mcp:
          targets:
          - name: go-guardian
            stdio:
              cmd: ${MCP_BIN}
              args: ["--db", "${DB_PATH}"]
          - name: github-advisories
            openapi:
              schema:
                file: ${OPENAPI_DIR}/github-advisories.json
              host: api.github.com
            policies:
              requestHeaderModifier:
                set:
                  Authorization: "Bearer \${GITHUB_TOKEN}"
                  X-GitHub-Api-Version: "2026-03-10"
          - name: nvd
            openapi:
              schema:
                file: ${OPENAPI_DIR}/nvd.json
              host: services.nvd.nist.gov
            policies:
              requestHeaderModifier:
                set:
                  apiKey: "\${NVD_API_KEY}"
          - name: go-vuln
            openapi:
              schema:
                file: ${OPENAPI_DIR}/go-vuln.json
              host: vuln.go.dev
GWEOF

  # Append New Relic MCP target if API key is set (remote Streamable HTTP — no Node.js bridge).
  if [[ -n "${NEW_RELIC_API_KEY:-}" ]]; then
    NR_REGION="${NEW_RELIC_REGION:-us}"
    if [[ "${NR_REGION}" == "eu" ]]; then
      NR_MCP_URL="https://mcp.eu.newrelic.com/mcp/"
    else
      NR_MCP_URL="https://mcp.newrelic.com/mcp/"
    fi
    cat >> "${GATEWAY_CONFIG}" <<NREOF
          - name: newrelic
            mcp:
              host: ${NR_MCP_URL}
            policies:
              requestHeaderModifier:
                set:
                  Api-Key: "\${NEW_RELIC_API_KEY}"
NREOF
  fi

  # ── Docker config (OpenAPI backends only — go-guardian stays on stdio via .mcp.json) ──
  GATEWAY_DOCKER_CONFIG="${GUARDIAN_DIR}/gateway-docker-config.yaml"
  cat > "${GATEWAY_DOCKER_CONFIG}" <<GWEOF
# Auto-generated by go-guardian plugin — regenerated each session.
# Docker mode: go-guardian MCP stays connected via .mcp.json stdio.
# This gateway proxies only the OpenAPI vulnerability backends.
binds:
- port: 3000
  listeners:
  - routes:
    - policies:
        cors:
          allowOrigins: ["http://localhost:3000"]
          allowHeaders: [content-type, mcp-protocol-version, mcp-session-id]
          exposeHeaders: [mcp-session-id, mcp-protocol-version]
          maxAge: 100s
        csrf:
          additionalOrigins: ["http://localhost:3000"]
      backends:
      - mcp:
          targets:
          - name: github-advisories
            openapi:
              schema:
                file: /openapi/github-advisories.json
              host: api.github.com
            policies:
              requestHeaderModifier:
                set:
                  Authorization: "Bearer \${GITHUB_TOKEN}"
                  X-GitHub-Api-Version: "2026-03-10"
          - name: nvd
            openapi:
              schema:
                file: /openapi/nvd.json
              host: services.nvd.nist.gov
            policies:
              requestHeaderModifier:
                set:
                  apiKey: "\${NVD_API_KEY}"
          - name: go-vuln
            openapi:
              schema:
                file: /openapi/go-vuln.json
              host: vuln.go.dev
GWEOF

  # Append New Relic MCP target to Docker config too.
  if [[ -n "${NEW_RELIC_API_KEY:-}" ]]; then
    NR_REGION="${NEW_RELIC_REGION:-us}"
    if [[ "${NR_REGION}" == "eu" ]]; then
      NR_MCP_URL="https://mcp.eu.newrelic.com/mcp/"
    else
      NR_MCP_URL="https://mcp.newrelic.com/mcp/"
    fi
    cat >> "${GATEWAY_DOCKER_CONFIG}" <<NREOF
          - name: newrelic
            mcp:
              host: ${NR_MCP_URL}
            policies:
              requestHeaderModifier:
                set:
                  Api-Key: "\${NEW_RELIC_API_KEY}"
NREOF
  fi

  # ── Auto-start gateway if opted in ────────────────────────────────────────
  GW_MODE="${GO_GUARDIAN_GATEWAY:-}"
  if [[ -n "${GW_MODE}" ]]; then
    GW_STARTED=false

    # Auto-detect: prefer Docker, fall back to native.
    if [[ "${GW_MODE}" == "1" ]]; then
      if command -v docker >/dev/null 2>&1; then
        GW_MODE="docker"
      elif command -v agentgateway >/dev/null 2>&1; then
        GW_MODE="native"
      fi
    fi

    if [[ "${GW_MODE}" == "docker" ]] && command -v docker >/dev/null 2>&1; then
      # Stop previous container if running.
      docker rm -f go-guardian-gateway 2>/dev/null || true

      docker run -d \
        --name go-guardian-gateway \
        -v "${GATEWAY_DOCKER_CONFIG}:/config.yaml:ro" \
        -v "${OPENAPI_DIR}:/openapi:ro" \
        -p 3000:3000 \
        -e "GITHUB_TOKEN=${GITHUB_TOKEN:-}" \
        -e "NVD_API_KEY=${NVD_API_KEY:-}" \
        cr.agentgateway.dev/agentgateway:1.0.1 \
        -f /config.yaml \
        >/dev/null 2>&1 && GW_STARTED=true || true

      if [[ "${GW_STARTED}" == "true" ]]; then
        echo "  go-guardian: agentgateway (docker) started on :3000"
      fi

    elif [[ "${GW_MODE}" == "native" ]] && command -v agentgateway >/dev/null 2>&1; then
      # Kill previous native instance.
      if [[ -f "${GUARDIAN_DIR}/gateway.pid" ]]; then
        kill "$(cat "${GUARDIAN_DIR}/gateway.pid")" 2>/dev/null || true
      fi
      agentgateway -f "${GATEWAY_CONFIG}" &
      echo $! > "${GUARDIAN_DIR}/gateway.pid"
      GW_STARTED=true
      echo "  go-guardian: agentgateway (native) started on :3000 (PID $!)"
    fi

    if [[ "${GW_STARTED}" == "true" ]]; then
      echo "  Add to settings: {\"mcpServers\":{\"go-guardian-gateway\":{\"type\":\"sse\",\"url\":\"http://localhost:3000/sse\"}}}"
    fi
  fi
fi

# ── Guard: skip if binary missing ────────────────────────────────────────────
if [[ ! -x "${MCP_BIN}" ]]; then
  exit 0
fi

# ── Generate session ID for cross-agent finding sharing ──────────────────────
SESSION_ID="$(uuidgen 2>/dev/null || python3 -c 'import uuid; print(uuid.uuid4())' 2>/dev/null || date +%s)"
# SECURITY: restrict session-id file to owner-only (fixes FINDING-23).
(umask 077 && echo "${SESSION_ID}" > "${GUARDIAN_DIR}/session-id")
export GO_GUARDIAN_SESSION_ID="${SESSION_ID}"

# Persist session ID so all Bash commands in this session can access it.
if [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
  echo "export GO_GUARDIAN_SESSION_ID=${SESSION_ID}" >> "${CLAUDE_ENV_FILE}"
fi

# Persist admin port so the admin UI starts in this session.
if [[ -n "${GO_GUARDIAN_ADMIN_PORT:-}" ]] && [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
  echo "export GO_GUARDIAN_ADMIN_PORT=${GO_GUARDIAN_ADMIN_PORT}" >> "${CLAUDE_ENV_FILE}"
fi

# ── Check for stale scans ───────────────────────────────────────────────────
if [[ -f "${DB_PATH}" ]]; then
  "${MCP_BIN}" --check-staleness --db "${DB_PATH}" --project "${PWD}" 2>/dev/null \
  | jq -r '
    if (.stale_scans | length) > 0 then
      "\n  go-guardian: stale scans detected",
      (.stale_scans[] | "  - \(.scan_type): last run \(.last_run_ago) ago (threshold: \(.threshold))"),
      "  Run /go to refresh all scans.\n"
    else
      empty
    end
  ' 2>/dev/null || true
fi

exit 0
