-- Automerge policy rules
INSERT OR IGNORE INTO renovate_rules (rule_id, category, title, description, dont_config, do_config, severity) VALUES
('AM-1', 'automerge', 'Automerge patch updates', 'Patch updates are low-risk and should be automerged to reduce PR noise.', '{"packageRules": [{"matchUpdateTypes": ["patch"], "automerge": false}]}', '{"packageRules": [{"matchUpdateTypes": ["patch"], "automerge": true, "automergeType": "pr"}]}', 'WARN'),
('AM-2', 'automerge', 'Automerge dev dependencies', 'Dev dependencies (test, lint, build tools) can be automerged for minor and patch.', '{}', '{"packageRules": [{"matchDepTypes": ["devDependencies"], "matchUpdateTypes": ["minor", "patch"], "automerge": true}]}', 'INFO'),
('AM-3', 'automerge', 'Lockfile-only automerge', 'Lock file maintenance PRs should always be automerged as they only update checksums.', '{}', '{"packageRules": [{"matchUpdateTypes": ["lockFileMaintenance"], "automerge": true}]}', 'WARN'),
('AM-4', 'automerge', 'Gate major updates', 'Major version bumps may contain breaking changes and should require manual review.', '{"packageRules": [{"matchUpdateTypes": ["major"], "automerge": true}]}', '{"packageRules": [{"matchUpdateTypes": ["major"], "automerge": false, "labels": ["breaking"]}]}', 'CRITICAL'),
('AM-5', 'automerge', 'Fast-track security patches', 'Security patches should be automerged with higher priority to reduce exposure time.', '{}', '{"packageRules": [{"matchCategories": ["security"], "automerge": true, "prPriority": 10}]}', 'WARN'),
('AM-6', 'automerge', 'Use PR automerge type', 'Use automergeType=pr for visibility. Branch automerge skips PR creation which loses review trail.', '{"packageRules": [{"automerge": true, "automergeType": "branch"}]}', '{"packageRules": [{"automerge": true, "automergeType": "pr"}]}', 'INFO'),
('AM-7', 'automerge', 'Require status checks for automerge', 'Automerge should only proceed after CI passes. Configure requiredStatusChecks or rely on branch protection.', '{"packageRules": [{"automerge": true}]}', '{"packageRules": [{"automerge": true, "automergeType": "pr"}], "$comment": "Ensure branch protection requires status checks before merge"}', 'WARN'),
('AM-8', 'automerge', 'Pin digest automerge', 'Digest pin PRs are safe to automerge — they lock to the exact image without changing the version.', '{}', '{"packageRules": [{"matchUpdateTypes": ["pin", "digest"], "automerge": true}]}', 'INFO');
