-- Grouping strategy rules
INSERT OR IGNORE INTO renovate_rules (rule_id, category, title, description, dont_config, do_config, severity) VALUES
('GRP-1', 'grouping', 'Group Kubernetes dependencies', 'K8s client libraries should be updated together to avoid API version mismatches.', '{}', '{"packageRules": [{"groupName": "kubernetes", "matchPackagePatterns": ["k8s.io/.*", "sigs.k8s.io/.*"], "groupSlug": "kubernetes"}]}', 'WARN'),
('GRP-2', 'grouping', 'Group testing dependencies', 'Test framework packages should be grouped to keep test infrastructure consistent.', '{}', '{"packageRules": [{"groupName": "testing", "matchPackagePatterns": ["testify", "gomock", "ginkgo", "gomega", "go-cmp"], "groupSlug": "testing"}]}', 'INFO'),
('GRP-3', 'grouping', 'Group linter dependencies', 'Linting tools should be grouped since they are often updated together.', '{}', '{"packageRules": [{"groupName": "linters", "matchPackagePatterns": ["golangci-lint", "staticcheck", "revive"], "groupSlug": "linters"}]}', 'INFO'),
('GRP-4', 'grouping', 'Group monorepo packages', 'Monorepo packages (e.g., @aws-sdk/*) must be updated atomically to avoid version conflicts.', '{"packageRules": [{"matchPackagePatterns": ["@aws-sdk/.*"]}]}', '{"packageRules": [{"groupName": "aws-sdk", "matchPackagePatterns": ["@aws-sdk/.*"], "groupSlug": "aws-sdk"}]}', 'WARN'),
('GRP-5', 'grouping', 'Use groupSlug for clean branches', 'Always set groupSlug alongside groupName for predictable branch naming.', '{"packageRules": [{"groupName": "testing"}]}', '{"packageRules": [{"groupName": "testing", "groupSlug": "testing"}]}', 'INFO'),
('GRP-6', 'grouping', 'Group Go module dependencies', 'Grouping all Go module updates reduces PR count and ensures go.sum consistency.', '{}', '{"packageRules": [{"matchManagers": ["gomod"], "groupName": "go-modules", "groupSlug": "go-modules"}]}', 'INFO'),
('GRP-7', 'grouping', 'Group Docker image updates', 'Docker base image updates should be grouped per Dockerfile for atomic rebuilds.', '{}', '{"packageRules": [{"matchManagers": ["dockerfile"], "groupName": "docker-images", "groupSlug": "docker-images"}]}', 'INFO');
