-- Ultra-high automation rules
INSERT OR IGNORE INTO renovate_rules (rule_id, category, title, description, dont_config, do_config, severity) VALUES
('AUT-1', 'automation', 'Pin GitHub Actions by digest', 'Actions should be pinned by SHA digest to prevent supply chain attacks, with a comment showing the version.', '{"packageRules": [{"matchManagers": ["github-actions"]}]}', '{"packageRules": [{"matchManagers": ["github-actions"], "pinDigests": true}], "extends": ["helpers:pinGitHubActionDigests"]}', 'CRITICAL'),
('AUT-2', 'automation', 'Track Makefile VERSION variables', 'VERSION= and TOOL_VERSION= patterns in Makefiles should be tracked with regex managers.', '{}', '{"customManagers": [{"customType": "regex", "fileMatch": ["(^|/)Makefile$", "(^|/)makefile$"], "matchStrings": ["(?:TOOL_|)VERSION\\s*[:?]?=\\s*(?:v?)(?<currentValue>\\d+\\.\\d+\\.\\d+)\\s*#\\s*renovate:\\s*depName=(?<depName>[^\\s]+)(?:\\s+datasource=(?<datasource>[^\\s]+))?"], "datasourceTemplate": "{{#if datasource}}{{{datasource}}}{{else}}github-releases{{/if}}"}]}', 'WARN'),
('AUT-3', 'automation', 'Pin Dockerfile base images', 'Multi-stage Dockerfile base images should use digest pinning for reproducible builds.', '{"dockerfile": {"pinDigests": false}}', '{"packageRules": [{"matchManagers": ["dockerfile"], "pinDigests": true}]}', 'WARN'),
('AUT-4', 'automation', 'Track go.mod tool directives', 'Go 1.24+ tool directives in go.mod should be tracked for updates.', '{}', '{"packageRules": [{"matchManagers": ["gomod"], "matchDepTypes": ["tool"], "groupName": "go-tools", "automerge": true}]}', 'INFO'),
('AUT-5', 'automation', 'Track shell script versions', 'Version variables in shell scripts (KUBECTL_VERSION, HELM_VERSION) should be managed by Renovate.', '{}', '{"customManagers": [{"customType": "regex", "fileMatch": ["\\.sh$"], "matchStrings": ["(?<depName>[A-Z_]+)_VERSION=(?:v?)(?<currentValue>\\d+\\.\\d+\\.\\d+)\\s*#\\s*renovate:\\s*datasource=(?<datasource>[^\\s]+)"], "extractVersionTemplate": "^v(?<version>.*)$"}]}', 'INFO'),
('AUT-6', 'automation', 'Track YAML config versions', 'Version fields in YAML config files should be tracked with regex managers.', '{}', '{"customManagers": [{"customType": "regex", "fileMatch": ["\\.ya?ml$"], "matchStrings": ["version:\\s*(?:v?)(?<currentValue>\\d+\\.\\d+\\.\\d+)\\s*#\\s*renovate:\\s*depName=(?<depName>[^\\s]+)(?:\\s+datasource=(?<datasource>[^\\s]+))?"], "datasourceTemplate": "{{#if datasource}}{{{datasource}}}{{else}}github-releases{{/if}}"}]}', 'INFO'),
('AUT-7', 'automation', 'Track CI pipeline tool versions', 'CI pipeline files often pin tool versions that should be managed automatically.', '{}', '{"customManagers": [{"customType": "regex", "fileMatch": ["\\.gitlab-ci\\.yml$", "\\.github/workflows/.*\\.ya?ml$"], "matchStrings": ["(?<depName>[a-z][a-z0-9-]+):(?<currentValue>v?\\d+\\.\\d+\\.\\d+)\\s*#\\s*renovate"], "datasourceTemplate": "docker"}]}', 'INFO'),
('AUT-8', 'automation', 'Automate everything with a version', 'If it has a version string, Renovate should track it. Use regex managers for any versioned tool or dependency not covered by native managers.', '{}', '{"$comment": "Philosophy: every version string in the repo should have a Renovate manager tracking it. Audit your repo for untracked VERSION= patterns."}', 'INFO');
